name:           Euterpea
version:        2.1.0
license:        BSD3
license-file:	  License
copyright:      Copyright (c) 2008-2022 Euterpea authors
category:       Sound, Music
stability:      experimental
build-type:     Custom
author:         Paul Hudak <paul.hudak@yale.edu>,
                Eric Cheng <eric.cheng@aya.yale.edu>,
                Hai (Paul) Liu <hai.liu@aya.yale.edu>,
                Donya Quick <donyaquick@gmail.com>,
                Jeremy Silver <jeremys@nessiness.com>
                Dan Winograd-Cort <dwincort@gmail.com >
maintainer:     Jeremy Silver <jeremys@nessiness.com>
bug-reports:    https://github.com/jeremander/Euterpea2/issues
homepage:       http://www.euterpea.com
synopsis:       Library for computer music research and education
description:
        Euterpea is a domain-specific language embedded in Haskell for
        computer music research, education, and development, providing
        both note-level and signal-level abstractions.  It is a descendant
        of Haskore and HasSound, and is intended for both educational purposes
        as well as serious computer music applications.  Euterpea is a
        wide-spectrum DSL, suitable for high-level music representation,
        algorithmic composition, and analysis; mid-level concepts such as
        MIDI; and low-level audio processing, sound synthesis, and instrument
        design.

extra-source-files:
  ReadMe.txt

dependencies:
  - base>=4
  - arrows>=0.4
  - array>=0.5
  - deepseq>=1.3
  - random>=1.0
  - PortMidi>=0.2
  - HCodecs >= 0.5
  - stm >= 2.4
  - containers>=0.5
  - bytestring>=0.10
  - heap >= 1.0
  - ghc-prim

library:
  source-dirs: .
  ghc-options: -O2 -funbox-strict-fields -fexcess-precision
  # extensions: CPP
  exposed-modules:
    - Control.Arrow.ArrowP
    - Control.SF.SF
    - Euterpea
    - Euterpea.Music
    - Euterpea.IO.Audio
    - Euterpea.IO.Audio.Basics
    - Euterpea.IO.Audio.BasicSigFuns
    - Euterpea.IO.Audio.CSound
    - Euterpea.IO.Audio.IO
    - Euterpea.IO.Audio.Render
    - Euterpea.IO.Audio.Types
    - Euterpea.IO.MIDI
    - Euterpea.IO.MIDI.ExportMidiFile
    - Euterpea.IO.MIDI.FromMidi
    - Euterpea.IO.MIDI.FromMidi2
    - Euterpea.IO.MIDI.GeneralMidi
    - Euterpea.IO.MIDI.MEvent
    - Euterpea.IO.MIDI.MidiIO
    - Euterpea.IO.MIDI.Play
    - Euterpea.IO.MIDI.ToMidi
    - Euterpea.IO.MIDI.ToMidi2
